import Head from 'next/head'

// これはHeaderではないかも？
// Header は、画面の上部に表示される要素のこと。
// Head はメタ情報（ページタイトルやページの説明など、Webサイトとして公開するときに、SEO関連でGoogleに対して提供する情報）を埋め込むためのもの。
export function Header() {
    return (
        <>
            <Head>
                <title>Todo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}
